events {}
http {
  resolver 127.0.0.11 valid=5s ipv6=off;
  upstream ml_workers {
    zone ml_workers 64k;
    server ml:8001 resolve;
  }
  server {
    listen 8001;
    location / {
      proxy_pass http://ml_workers;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
    }
  }
}
